# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2cd9ab181325569d9a24ac9464324c079760be3901d869793bef03d8527da30557d789d3c7076086888915c2cc3803b0215ce7d76b96efe7ce46b3226e309006

test:
  secret_key_base: e90c7401cb4d2459bbd76b9f6817b6c5e488ac2d751c18dbebc1a076148e49155d200352eca4d1c229a7614341b8499fe9e9132efa3e7adffee21bdcec166aa1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
